name: flet_confetti
description: Flet FletConfetti control
repository: https://github.com/MyGithubAccount/flet-confetti/src/flutter/flet_confetti
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-confetti

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  confetti: ^0.8.0
  flet: 0.28.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
